---

- name: Smartcard Workstation Install
  hosts: all
  tasks:
          - name: List files and folder in home directory
            shell: 'ls /var/lib/awx/projects'
            register: command_output

          - debug:
                var: command_output.stdout_lines
