---

- name: Smartcard Workstation Install
  hosts: all
  tasks:
    - name: Execute the script
      command: ls -l
      register: command_output

    - debug:
      var: command_output.stdout_lines
